### ISSUE TITLE
Run help

### ISSUE THREAD

**Issue by Yu-Wang-0801** [researchmm/TTSR#10]
Hello, I encountered some problems while reproducing this code, and I hope to get your help. Thank you
1. When I am training, the code will have such an error, as shown in the figure. I guess it might be a path problem, but I still have this problem with the data set I stored according to your data preparation style.
2. When I commented out the evaluation code reported above, the training runs normally. But I found that when testing, you need to test one by one, not multiple datasets at the same time.
![image](https://user-images.githubusercontent.com/49390007/88894295-3aa5aa00-d27a-11ea-825b-a02dc1ebe4eb.png)

**Comment by FuzhiYang** [comment]
1. It seems that this problem is caused by wrong validation data path. Since your training process is normal but the evaluation process   has an error. Could you show me the details of your data structure style?
2. Yes, "eval" mode is for evaluation on some test datasets, while "test" mode is for single pair of LR and Ref.

**Comment by Yu-Wang-0801** [comment]
Hello, thank you for your help, I have solved this problem, it is indeed a path problem.

**Comment by 123dddwn** [comment]
@Yu-Wang-0801 How did you solve path problem? Thank you!
