### ISSUE TITLE
The PSNR on Urban100 is different from the paper?

### ISSUE THREAD

**Issue by yangfan97** [researchmm/TTSR#6]
Thank you for your sharing! I have trained RCAN on the CUFED5 training set, and the PSNR I got on Urban100 is 26.15dB. In the paper, the PSNR on Urban100 of RCAN is 25.42dB. When I was training RCAN, I just followed  the setting in SRNTT. Maybe there are still some differences between our setting. Could you please tell me your detailed setting for training RCAN?

**Comment by FuzhiYang** [comment]
Thank you for your interest in our work! Although I cannot remember all the training details when training RCAN since it has been a long time passed, there are some important details that may help you:

1. Following the setting of SRNTT, we use scipy.misc.imresize to apply bicubic interpolation for LR generation. Please note: this function has been depreciated in SciPy 1.0.0, and was removed in 1.3.0. You can use PIL's resize function instead as in our code. Matlab's imresize which has unique antialias is not adopted here.
2. The metrics PSNR and SSIM are evaluated on Y-channel in YCbCr image.
3. When training RCAN_x4, there is no pre-training on RCAN_x2 to ensure fair comparison.

Also, different initialization and training bias will influence the final results. Besides, there may be other training details that are not listed here or what we cannot remember. By the way, from our experimental experience, the backbone of recent RefSR methods such as TTSR, SRNTT, etc is not optimal, where a progressive upsampling architecture with ResBlocks applied. It is encouraged that you can try more possible effective backbones such as RCAN, etc that have an architecture with only the last few layers to upsample.

**Comment by tejaskhot** [comment]
Hi @FuzhiYang !
It looks like the [code used for computing PSNR](https://github.com/researchmm/TTSR/blob/master/utils.py#L88) is using all channels of the image and not just Y.

**Comment by FuzhiYang** [comment]
Hi @tejaskhot 
Both PSNR and SSIM are calculated on Y channel in the code.

**Comment by scutlrr** [comment]
> Thank you for your sharing! I have trained RCAN on the CUFED5 training set, and the PSNR I got on Urban100 is 26.15dB. In the paper, the PSNR on Urban100 of RCAN is 25.42dB. When I was training RCAN, I just followed the setting in SRNTT. Maybe there are still some differences between our setting. Could you please tell me your detailed setting for training RCAN?

Hello, could you please tell me how do you train the RCAN? I use the [official code](https://github.com/thstkdgus35/EDSR-PyTorch) to train the model on the CUFED5 dataset, and the PSNR on CUFED5 testing datasets is smaller than yours. Do you modify any setting in code except for data-dir in option.py?
