### ISSUE TITLE
Questions about the implementation

### ISSUE THREAD

**Issue by wl082013** [researchmm/TTSR#7]
Hi nice work, 
I am wondering about the CSFI module.
As this module involves downsampling and upsampling,  did you resize all training and test images with even numbers (\e.g. 256), which can be divided by at least 4? 
My concern is CSFI module can not deal with image with any size, so I am curious about how you dealt with the issue.
Thanks for your reply.

**Comment by FuzhiYang** [comment]
The downsampling and upsampling layers will indeed contraint H and W of the image. Because out model is x4 scale super-resolution, so we constraint the images that can be divided by at least 4 using crop. This can be referred in the evaluation and test parts of our code:
1. https://github.com/researchmm/TTSR/blob/master/dataset/cufed.py#L148
2. https://github.com/researchmm/TTSR/blob/master/trainer.py#L175
